const texts = [
"",
"That’s it! That’s how you play “Triangle or Square”.",
"I could have made the two buttons the same shape (like a blue and a red squares).",
"But then, this game wouldn’t be color-blind friendly, and I value accessibility! Yay!",
"Wait… did I say “this game”? How do we know this is a game? 🤔",
"Couldn’t it be… a pizza?",
"A bird? A plane? Superman???",
"No this is silly, we know it’s none of these things.",
"(You have no way of signaling with the buttons presented to you what your opinion is. Sorry, this is a monologue)",
"If your input doesn’t matter in the end, is it still a game?",
"Many people will say meaningful decisions are at the core of what constitutes a game.",
"I used to be super into the definition problem of what’s a game (and what’s art - which I won’t get into today because one definition problem is depressing/annoying enough).",
"I got tired of it quickly because you always hear the same arguments and after a while it stops being playful and fresh.",
"Anyway, when I was young and still amazed by these conversations, I read many “classic” definitions of what a game is.",
"One of them is “a game is a series of interesting decisions” (by Sid Meier, the creator of Civilization, among other cool things)",
"If you take it as a poetic definition, I love it. And of course someone who makes strategy games would view games like a series of interesting decisions.",
"I have two problems here though: what’s “interesting”, and what’s a “decision”?",
"Calling something interesting is *highly* subjective. We don’t like that in a definition.",
"Needless to say, I don’t think a lot of people find “Triangle or Square” interesting.",
"If it weren’t for the texts, I doubt you would have played it for this long. <a href=’https://danodz.github.io/smallGames/triangleOrSquare/’>Here’s a vanilla version of this game</a> with just the triangle and the square; see how long you can go (if you’re interested in playing such a game at all in the first place, which I doubt).",
"But the fact is, there *could* be someone out there who finds that game interesting. And who am I to tell them it’s not!",
"Maybe they get super excited wondering if they should press the square button sometimes. You know, just to see what happens.",
"And if so, how many times should they press the red square.",
"Is that an interesting decision to make?",
"Or maybe they want to win 100 times without ever losing, send it to their friends without context and brag about how much they rock at this game. Or not share it and just be content with themself.",
"And so on and so forth.",
"Moving on to other examples than “Triangle or Square”, things from your daily life can be a series of *interesting* decisions: doing the groceries, commuting somewhere, planning a date, and so on. All things we don’t typically consider games.",
"But it can also *not* be interesting to you. Anyway, you get my point, you know what subjectivity is.",
"And then, “decision”. I know it sounds silly to ask, but what’s a decision?",
"In a strategy game, it’s obvious what it is. Take chess: what piece do I move to what tile? Kaboom. Tons of decisions to make every time you play.",
"But there are other game genres. Let’s take a platformer like Super Mario Bros. (the 2D ones for simplicity’s sake).",
"You move left to right, you jump from platform to platform, and you avoid getting killed in the process.",
"At a first glance, you’d say no decision is involved. Lots of skills are required, decision-making simply is just not one of them.",
"And you would BE RIGHT. Stop thinking further. Your first guess was true. It’s common sense.",
"But some people will find a way to defend Meier’s definition (either as a fun debate challenge, or out of, I don’t know, respect for his authority? Being scared of having to come up with another definition if we let go of that one?)",
"They will say that a game like Mario involves a lot of micro-decisions. You “decide” when you jump. You “decide” when you move.",
"I think that’s a stretch.",
"And I think the people defending that point of view also know deep down that it’s a stretch.",
"I am not friends with people who hold this argument.",
"Let the definition go. It’s not sacred. Sid Meier doesn’t know what he’s talking about.",
"(In his defense, none of us do).",
"By the way, if this text is getting longer than you expected, you can stop at any time. It will resume from where you left the next time you launch it. ",
"It will only go back to the beginning if you click the restart button on the top-left.",
"And if you want to read the text by itself, without having to play Triangle or Square to work through it, you can do so by pressing the button on the top-right.",
"I’d only recommend doing that after playing through it once though.",
"Anyway, I’ll spare you the other commonly explored definition of what a game is. They all more or less come down to the same things:",
"Solving a problem, making decisions, being restricted by rules, yadda yadda.",
"They often include the notion of being in an artificial context, which I like  because otherwise school and other such things would count as a game, and that’s not ok.",
"Instead of going with a general one-sentence definition, I like to break down what games are into multiple characteristics.",
"(We won’t go into this other conversation, but that is also how I like to approach how to define a sandwich).",
"(Exercise for the reader: come up with an example of something that is both a game and a sandwich).",
"A characteristic that people will often mention is that a game needs to present a challenge.",
"You might now be thinking “Hum I’ve been clicking at this triangle for minutes now without any problem, there’s no challenge here”.",
"Well think again, pal.",
"Both of those shapes have a base of the same length  (it’s a base of 200 pixels, if that information matters to you).",
"If you remember your geometry from high school (no shame if you don’t, most people don’t use it on a daily basis), you’d know the area of a square is its base times itself (b * b)",
"Whereas the area of a triangle is its base times its height divided by 2 (so b * h / 2), and here our triangle is equilateral so it’s basically b * b  / 2.",
"(No worries if you didn’t follow any of this, the takeaway is that the triangle is smaller than the square).",
"All that to say, the area of the triangle is half that of the square, and it’s therefore two times harder to hit than the square.",
"So you are more likely to lose than to win, and so “Triangle or Square” presents indeed a challenge and is therefore a game.",
"You might be thinking “and you were the one affirming that saying there are micro-decisions in Mario is a stretch?”",
"I agree. The point I just made about Triangle or Square’s difficulty is a stretch too. I do not believe it’s really challenging.",
"But, plot twist, I also do not believe something needs to be challenging to be a game.",
"(We will put aside the fact that “challenging” is subjective, because we already had that conversation with “interesting”, and we can have it again with basically every term that will be used to define what a game is).",
"I don’t want to go the “is chess challenging? Is tic-tac-toe challenging?” route, so I’ll take examples that are unambiguously not challenging.",
"Luck-based games are a good example of that. Snakes and Ladders, TROUBLE and War (Battle) are all games that require no skill whatsoever.<img src='res/snakesLadders.jpg'><img src='res/trouble.jpg'><img src='res/war.jpg'>",
"Except if you have a very peculiar view of the word that believe luck is a skill and that it can be fostered, you’d be forced to admit there exist games that aren’t challenging in any way.",
"(Or maybe you are consistent and disagree that any of the three games examples I just mentioned are in fact games; you’d go against their typical classification and popular belief, but I’d respect that).",
"By the way, just to link that back with the definition saying games are a series of interesting decisions: luck-based games are also a prime example of how a game can involve no decision at all.",
"And I heard some people in the past arguing: “well you make the decision of playing or not”.",
"I think at least some of them mean it seriously, but others probably are making that argument out of bad faith.",
"Either way, that’s ludicrous. You can say that about any activity; which would imply everything you do is a game and render the word meaningless.",
"Anyway, that doesn’t make sense: the activity / the game starts after you’ve decided to enter it. What happens before is external to the activity.",
"(And this argument is a textbook example of why I find these conversations painful, in case you were wondering).",
"So there you go. We debunked the first commonly accepted characteristic of games, that they have to be challenging.",
"By the way, if you have at least 20 victories at “Triangle or Square'' by now, you’re owning this.",
"(I honestly have no idea how many games you should have played to get to this point of the text, and I won’t bother figuring it out).",
"I just figured it’d be *fun* to give you some kind of feedback on your performance.",
"Speaking of *fun*, another cool thing to deconstruct is that games need to be fun.",
"I know I just said we wouldn’t have the subjectivity conversation again. It’s gonna be challenging (hehe) not to with this one.",
"Why would games be constrained to being fun? I’m honestly envious of other art forms that don’t have an intent imposed on them.",
"Like if I were to write a novel, no one would say “oh it has to be fun”.",
"Madame Bovary is not fun. Frankenstein is not fun. 1984 is not fun. (Well except if ennui, horror or authoritarianism are fun to you).",
"They’re not fun, but they accomplish something else. And thank god we allow them to do that, because otherwise we would lose an important chunk of our culture.",
"A novel has the freedom to be whatever its creator wants it to be. Can games have the same privilege, please?",
"Not only can novels have whatever intent and still be well-regarded, but it will never compromise their status as a novel. And the same goes for most art forms, as far as I know.",
"Like can you imagine asking James Cameron if Titanic is a movie? Because it’s not *fun*?!?",
"I don’t know, maybe filmmakers debate about the legitimacy of some formats or whatever. ",
"Maybe they wonder if TikToks are short movies (disclaimer: I think they are)",
"(Which says nothing of their quality)",
"Let’s say we have a broad definition of what “fun” is, by which we can mean something is entertaining, enjoyable, engaging, whatever. I think we can say all the books and movies I just mentioned are engaging or entertaining, even if not *fun. But being any of those things is a *quality*, not a determining characteristic.",
"Like if I try making an entertaining game and I fail, I still made a game, right? It’s just a bad one.",
"For instance, ideally, food should be delicious. However, if I cook a meal and it tastes terrible, you won’t argue I made a meal; you just won’t let me cook for you again.",
"Conclusion: games don’t have to be fun, because imposing *one* intent on a whole medium is super limiting, it narrows down the kind of experiences creators can make and players can consume, and* that’s* not fun.",
"By the way, are you having fun right now? Do you find these thoughts amusing or interesting or whatever?",
"If you don’t value what you’re doing at the moment, please go do something else. Your time is too precious to spend it doing things you don’t truly enjoy.",
"(Yes this game just made sure you’re consenting to continue, because this is how I rule).",
"I’m also asking because people say a game is a “voluntary” activity (it’s part of many definitions).",
"That’s not a definition, that’s just decency.",
"If I’m forced to watch a movie, does it stop being a movie? No, but it’s wack.",
"I find it a bit weird that how you enter the activity would define the nature of the activity.",
"But that makes sense for people who define games as a *state of mind* rather than a *set of rules*. ",
"We won’t give those people a voice here because they’re too brainy for us.",
"So, we were speaking of things I envy about other artistic media, and I’ll take that opportunity to go on a tangent.",
"Another conversation other media don’t really need to have and that I wish I didn’t have this often is whether or not their medium is art.",
"I used to be part of an experimental gamemakers collective, and we gave two interviews to journalists in which I participated.",
"Each time, we were asked if we think video games are / can be art.",
"And of course, if you want to determine whether something is art (or anything really), you have to define what art is.",
"So, while I’m sure that creators in other art forms have to go through the draining conversation of what art is through their academic years, *we* have to go through it for the rest of our career.",
"I doubt filmmakers get asked throughout all of their career if movies are art.",
"I don’t even care if video games are considered art or not in the end. It’s not the legitimacy of my creative outlet as art that bothers me. It’s that I’m not interested in having these dry conversations again and again.",
"Something can be valuable (economically and culturally) without being art. Like sports, for example.",
"When my peers ask “when will video games finally be recognized as art”, I suspect they’re actually asking something else.",
"They might be asking “When will society take my craft seriously”, and being recognized as an art is just a means to achieve that, not the goal itself.",
"They might be asking “When will my parents take me seriously”.",
"(I personally know people whose parents thought playing / making video games was worthless until they learned you can make (good) money with it).",
"(That’s super depressing, but it goes to show that some people can value your craft for extrinsic reasons without valuing it intrinsically; and they probably never will).",
"Or, more pragmatically, they might be asking “when will I be able to ask the government for art-related grants”.",
"Right now, where I live, you can ask for tech-related grants or entrepreneurship-related grants when making a video game, but not art-related grants.",
"So while wanting to be considered an art might be considered a noble pursuit, it can actually be just a way to get more money.",
"(Which is not an evil goal; you do need money to live! And to make those damn games!)",
"Ah, I always try to come back to “Triangle or Square” after finishing a topic, and I guess we’re at that point.",
"I do it so there’s a reason you’re playing it and that it’s not just a gimmick or an excuse for me to ramble on.",
"Hum, so is “Triangle or Square” a work of art? It has visuals and sounds, both of which are art forms in themselves. So I guess the sum of works of art can only be a work of art itself?",
"No joke, this is one of the main arguments I hear to say video games are art.",
"That, or something along the lines of “Go play Journey and tell me this isn’t art” - you can replace Journey by any critically-acclaimed so-called “art game”.",
"I want to hear someone say “Go play Triangle or Square and tell me this isn’t art” with a serious face (not this version, which comes with an intellectual commentary and could be considered art; I’m talking about <a href=’https://danodz.github.io/smallGames/triangleOrSquare/’>the vanilla one</a>).",
"I want to see the confused reaction of the other person, playing the game and trying to figure out if there’s something they don’t “get”.",
"(People interested in those questions usually worry a lot about “getting” a piece they’re presented with).",
"So yeah, is Triangle or Square a work of art? Should I have applied for grant money to make it?",
"Could it be exposed in a museum?",
"Will my parents be proud of me?",
"Are YOU proud of me? (If so tell me in the comments or send me a message if you know me personally - I crave attention thank you).",
"(The last bit is not even sarcastic or anything).",
"And let’s be honest: when you create something, normally you don’t wonder *what* it is. You just make it.",
"When someone experiences one of my “games”, what’s important to me? And to them? To me, it’s that they’re having a good time, that they got the message (if the game had one), and that they get to know a little bit more about me.",
"And to them? I don’t know.That’s different for everyone.",
"But in either case, I don’t think them seeing my work as art is something we pursue. It doesn’t change their experience (or at least it shouldn’t).",
"If I was worrying that much that my public sees my work as art, I’d probably not be focusing on the right thing and would not be creating the best piece I could.",
"...Well this was a long-ass tangent on the status of games as art. Back to our regularly scheduled program.",
"Open any “intro to game design” book. It will inevitably have a section on “what’s a game”.",
"I’m reading these books to learn how to make them, not to question their nature.",
"Do filmmakers have to go through this bullshit? No; a movie is a sequence of pictures that (often) give the impression of movements. They don’t spend paragraphs on it.",
"They don’t come up with definitions like “a movie is a series of interesting graphical feelings”. -And then have people debunk what interesting, graphical and feelings mean and if it really applies to all movies, or if it applies to things that aren’t movies.",
"Yeah, I should have become a filmmaker instead. Less useless conversations.",
"The only problem is that I don’t like movies that much and I love video games tremendously.",
"Oh and that my programming skills don’t really apply in making movies. And I can’t think of a role that I would enjoy or be good at.",
"Ok there are several good arguments against me working in films, but still. I’ll entertain the idea for now.",
"Hey, so what’s up with Triangle or Square? Are you losing more often than you’re winning?",
"I hope you’re losing more; the game is pointless, so why pride yourself in winning more anyway!",
"(I could have checked what’s your “score” and made a custom dialogue based on that).",
"(And while that would not have been hard to implement, I wanted to keep this game as simple as possible).",
"Ok when you reach 69 victories I’ll say “nice”.",
"The meme is worth the extra work.",
"Maybe it’s too late and you already went beyond 69 victories, in which case I’m slightly sorry.",
"Moving on.",
"Another popular-ish characteristic in games definition is that the outcome should be unpredictable.",
"What this basically means is that the players don’t know how each of their actions will turn out.",
"It might be less obvious what’s problematic with this one.",
"If we accept that as a characteristic, many games we typically consider as such wouldn’t be eligible.",
"For example, Tic-Tac-Toe is a solved game. What that means is that if two perfect players compete against each other, the outcome will always be the same: a tie.",
"Not only would the final outcome be the same, but pretty much the whole game would unfold in the same ways every time.",
"And it’s not like playing Tic-Tac-Toe perfectly is a hard skill reserved only to an elite: a child can easily learn it (with or without assistance from an adult).",
"So is Tic-Tac-Toe a game? Is it a game to some people (those who haven’t learned its strategy and still have unpredictable outcomes) and not to others? Would that mean it could be a game to you at some point in your life until it’s not?",
"(I actually know someone who does indeed defend that position. I’m not saying it’s wrong - I’m just saying you actually have to accept these odd conclusions to affirm that a game must have an unpredictable outcome. If they’re weird to you, maybe you do not in fact think it’s a defining characteristic of games).",
"Also, stating the obvious, but Triangle or Square is not considered a game under that definition.",
"(If at this point you haven’t noticed that the game always responds the same way to your inputs, now is the time to realize that. Appreciate the consistency of the game, the security of always knowing how things will end).",
"Alright.",
"So far, I covered in great length what I *don’t* think a game is. It doesn’t necessarily involve decisions, it’s not always challenging, and it doesn’t have to be fun. It doesn’t have to have unpredictable outcomes.",
"(And games may or may not be art but we don’t care about that today, if ever.)",
"So what do I think games *are* then?",
"And I think it’s only fair that I answer this. It’s easy to criticize other people’s ideas, but if you don’t show yourself vulnerable and share yours, you’re not saying much in the end.",
"(That being said, normally when people ask me this in real life, I tell them I’m tired of discussing this and I’ll only agree to share my definition if they promise not to ask follow-up questions or present counterarguments).",
"(I know those are harsh conditions).",
"(Most of the time, they end up not respecting those conditions, and I try my best not to answer their counterarguments, but I’m weak and I always take the bait).",
"Anyway.",
"I don’t think I hold the truth to that what defines a game, but here are the three characteristics that I personally think *all* games, and *only* games, share:",
"1. They have rules.",
"2. They have a victory and/or a losing condition.",
"3. They are detached from reality / mostly unimpactful.",
"(For the last one, I’m still trying to find a wording that I’m satisfied with).",
"Let’s explore the boundaries of this definition with a few examples.",
"An example that respects my definition is Tic-tac-toe.",
"Tic-tac-toe has rules, a clear victory condition, and after a game of tic-tac-toe, my life pretty much resumes to what it was before.",
"An example that *doesn’t* respect my definition is going to school.",
"Going to school has rules, I guess it has a victory condition (you pass your classes / graduate), but it’s very much not detached from reality.",
"I have to be physically there in person at a regular schedule, if I fail a class this will delay when I graduate (if you lose at tic-tac-toe, there usually are no consequences), if I ever graduate I might start a new career, etc.",
"Some people have a definition of games that is similar to mine, except they leave out the last condition. Those who do that open the door to including things like going to school as games.",
"(By the way, if you want to be super academic about it, that concept of having something “detached from reality” is called the magic circle in game design literature. Feel free to google it and/or use it in conversations to sound smart).",
"We’re gonna cover one last, slightly more controversial, example: playing with dolls.",
"If I play with dolls, I’m not playing a game. I’m playing with a toy; I could use that toy as a game component to make a game by adding rules and such, but in itself it’s not a game.",
"Like if Patrick from SpongeBob were to ask you if mayonnaise is a game, you should answer him that no mayonnaise is not a game. But it can be an incredible, messy game component. <img src='res/mayo.jpg'>",
"To give a more concrete example that uses actual game components (for people not familiar with game design terminology), in Monopoly, the dice, the board and the pawns are game components. But no one would say for example that the thimble pawn is in itself a game; it’s just a pawn (and objectively the coolest one).<img src=’thimble.png’>",
"To get back to my example of playing with dolls, some people argue that because you use the word “play”, necessarily a game is involved.",
"Sometimes, they extend their argument to pretty much anything that uses the word “play”: to them, a play is a game. Playing guitar is a game.",
"And I guess to them, when Britney Spears says “Oops I did it again, I played with your heart”, she is also playing a game.",
"I don’t like that argument, because it’s very language-specific. “A play” in French is “Une pièce de théâtre” (a theater piece). “Playing guitar” in Spanish is “Tocar la guitar” (touch the guitar).",
"(Two years of studying Spanish in college and the only use I find for it nowadays is using “tocar la guitar” in an argument about whether or not something is a game. Worth it.)",
"Are you telling me that something could be a game in English but not in French and in Spanish? And more generally, that something could be a game in one language and not in another? That’s a very weird point to defend (but I love bold statements, so if you do hold that position, all respect to you).",
"Or maybe you’re very anglo-centric, and because something can be said in English, then it’s just a universal truth (I love bold statements but I despise anglo-centricism and more generally eurocentrism, so I would NOT respect that position).",
"Or you believe that if you can say you “play” with a thing in a language, any language, then that action is indeed a game and it applies to all languages. Like you would consider the same to be true if I could say I “play potatoes”(which could mean I peel potatoes in that hypothetical language) and would therefore consider potatoes a game. ",
"The argument is getting weirder with every iteration (and you would need to be fluent in *all* languages to affirm whether or not something is a game).",
"And with that logic, I could technically invent a language in which the only verb is “play”, and so you can play anything, and therefore anything is a game now.",
"Anyway, to get back to the definition itself, I know it has flaws. Well, specifically the third point; I don’t believe there are any in the first two.",
"It opens the door to many counterexamples. Like I consider soccer to be a game (it has rules and a victory condition). You can resume your life normally after playing a game of soccer - It is impactful though in that it will improve your cardio.",
"And playing video games and board games sharpen other skills - it’s not the exclusivity of sports games. So it’s not like it’s just one weird edge-case.",
"It’s a tradeoff to me. Either I keep this third condition and allow this easy rebuttal, or I don’t and then school and other non-playful things are games. Bleh.",
"If someone ever has a solution to this, I’m very much all ears.",
"(Even though I know the real solution is to admit we are only mere mortals and will never find a satisfactory answer to “what is a game”).",
"Maybe defining what’s a game IS a game.",
"(And there’s no winner. You lose by engaging).",
"Let’s say we all universally accept my definition of games as THE definition.",
"The first thing we would do is celebrate never having to spend any second thinking about this ever again.",
"The second thing we would do is become incredibly confused as to what we should call some softwares that were commonly viewed as video games, but aren’t games under that new definition.",
"For instance, The Sims doesn’t have a victory condition (you could set up your own goal, but that’s another side-game you would be making; The Sims in itself doesn’t provide a goal). What do we call it now?",
"We can just call it a software. Or an interactive simulation. Or create a new word, we never have too many of those.",
"I heard people say we could call them an “experience”. This unjustifiably infuriates me. Everything is an experience.",
"Eating a meal is an experience. Walking down the street is an experience. Getting the flu is an experience.",
"If we want to refer to something more specific, we can’t use such a generic term.",
"But for now, I’m not too concerned about what that term would be.",
"I want to move on to another related topic: some people consider it would be gatekeeping to say some things are games and others aren’t, and that we should avoid doing it.",
"Gatekeeping is a bad thing, but I don’t think categorizing things exactly counts as gatekeeping. Only being able to learn how to program through expensive university classes is gatekeeping / sexism and racism in the industry is gatekeeping; saying that something is not a game, while still allowing and celebrating its existence, is not gatekeeping.",
"I can consider that something is not a game while seeing its merit and its artistic value, and thinking of it as a valuable work.",
"For the last time; think of how this debate would make no sense in any other medium; saying that a textbook is not a novel would be a pretty normal take. They’re both books, sure, but otherwise they’re pretty distinct and one would not be mistaken for the other. I’m not gatekeeping by saying The Lord of the Rings is not a textbook.",
"Similarly, I’m not saying The Sims is better or worse by saying it’s not a game. I’m not saying it has more or less value.",
"I’m not saying Microsoft Word is bad when I say it’s not a game. The Sims and Microsoft Word can be great softwares while not being video games.",
"Now, believe it or not, but some people would call Microsoft Word a game.",
"We’re now gonna address a pretty extreme take of this debate.",
"I’ve covered some definitions that I didn’t like because they imply that everything is a game.",
"Well, some people do explicitly have that take. They’ll say that anything you call a game is a game. ",
"Ok sure, but then anything I call a cat is a cat",
"Anything I call a chair is a chair.",
"Anything I call a sandwich is a sandwich (don’t get me started on that one).",
"I think the sentiment behind that definition is sweet and inclusive, but it’s not very practical. I also don’t think that’s how the people who adopt it treat every word.",
"I did hear a pretty good defense for it though.",
"Someone I respect a lot said that anything is a game, because people with a richer vocabulary could work their way into pitching that anything is a game",
"You don’t believe petting a cow is a game? Give an academic 10 minutes, and they’ll convince you otherwise.",
"So if we don’t allow everyone to say that whatever they made is a game, then we leave that power to an elite.",
"And we don’t want that.",
"I think that makes sense to me. That even checks out with how I’ve defended “Triangle or Square” as a game since the beginning. I’ve been using some bad-faithed, silly intellectual arguments.",
"I’ve defended Triangle or Square like an academic would.",
"(Remember that time when I said Triangle or Square is challenging because a triangle with the same base as a square is half its area? What a good time).",
"I don’t really know what to make of this argument yet.",
"At the end of the day, I’m still not a fan of saying anything can be anything.",
"But I’m also not a fan of discussing semantics for too long, and yet here we are, 5,437 words in.",
"So, I said that this definition is not very practical. What do I mean by that?",
"I mean that it’s not how people actively use the word in their day to day life.",
"If I invite you over to play a game without specifying which one, and the game turns out to be tic-tac-toe, you might be disappointed in that it’s a boring game, but you’re gonna agree I delivered on what I promised.",
"I did indeed invite you to play a game.",
"If I invite you over to play a game and the game turns out to be cooking sushis, you’re gonna be frustrated (regardless of whether or not you like cooking sushis). That’s not what I promised.",
"You’ll trust me less, and you won’t be sure what I mean next time I invite you to play games.",
"(Except maybe if you’re a really adventurous person who loves randomness?)",
"Another example: imagine you ask someone what’s their favorite game, and they answer it’s taking a walk. Or complimenting their friends. The latter is super sweet, but in both cases, you won’t have the information you were actually looking for. And that’s very frustrating.",
"Yeah, frustration is definitely a good metric for definitions.",
"(Meme idea: there are two wolves inside of you. One finds definition discussion pointless, counterproductive and tiring, the other enjoys specifically their pointlessness and counterproductiveness. But this one is also tired.)",
"Anyway, that’s all I had to say on the matter.",
"(Actually not true; but I don’t want this to go on for 10 hours)",
"Thank you for reading all the way through this thing. I hope you got something out of it, if only a smile.",
"You can comment below what you think a game is (I’ll probably ignore it).",
"And you’re free to play the game for as long as you like, even though there’ll be no more text!",
"Goodbye, take care of yourself and others <3"
]
